---
- name: Apt Install Apache
  apt: name=apache2
  tags:
    - apache
    - install

- name: enable FastCGI module
  apache2_module: name=proxy_fcgi
  tags:
    - apache
    - install

- name: enable Rewrite module
  apache2_module: name=rewrite
  tags:
    - apache
    - install

- name: Remove default webapp
  command: 
    a2dissite 000-default.conf
  notify:
    restart Apache
  tags:
    - webapp
    - install