---
- name: Apt Install Apache
  apt: name=apache2
  tags:
    - apache
    - install

- name: enable FastCGI module
  apache2_module: name=proxy_fcgi
  tags:
    - apache
    - install

- name: enable Rewrite module
  apache2_module: name=rewrite
  tags:
    - apache
    - install

- name: Enable ssl
  apache2_module: name=ssl

- name: Create ssl directory
  file: path=ssl state=directory

- name: Copy ssl certificate files
  copy: src={{ item }} dest=/etc/apache2/ssl/{{ item }}
  with_items:
    - proactit.key
    - proactit_io.ca-bundle.crt
    - proactit_io.crt

- name: Remove default webapp
  command: 
    a2dissite 000-default.conf
  notify:
    restart Apache
  tags:
    - webapp
    - install

