---
- name: Create group
  group: name=website state=present
  tags:
    - user
    - install

- name: Create User
  user: name={{ APPNAME }} group=website home=/home/{{ APPNAME }} shell=/bin/bash
  tags:
    - user
    - install

- name: Create user home
  file: path=/home/{{ APPNAME }} state="directory" owner={{ APPNAME }} group=website mode=0755
  tags:
    - user
    - install

- name: Create user ssh directory
  file: path=/home/{{ APPNAME }}/.ssh state="directory" owner={{ APPNAME }} group=website mode=0700
  tags:
    - user
    - install

- name: RSA keys
  copy: src=id_rsa dest=/home/{{ APPUSER }}/.ssh/id_rsa owner={{ APPNAME }} group=website mode=0600
  tags:
    - git
    - install    
