---
- name: setup PHP Composer
  shell: creates=composer.phar chdir={{ APPCOMMONDIR }}
    curl -sS https://getcomposer.org/installer | php
  tags:
    - symfony
    - install

- name: setup framework installer
  shell: creates=symfony.phar chdir={{ APPCOMMONDIR }}
    curl -LsS http://symfony.com/installer > symfony.phar
  tags:
    - symfony
    - install

- name: make framework installer executable
  file: path={{ APPCOMMONDIR }}/symfony.phar mode='ugo+x'
  tags:
    - symfony
    - install

- name: symlink PHAR files
  file: src={{ APPCOMMONDIR }}/{{item}}.phar dest=/usr/local/bin/{{item}} state=link
  with_items:
    - composer
    - symfony
  tags:
    - symfony
    - install
    